Vagrant.configure("2") do |config|

  (1..2).each do |i|
    config.vm.define "web0#{i}" do |centos|
      centos.vm.box = "centos/8"
      centos.vm.hostname = "web0#{i}"
      # centos.vm.network "public_network", ip: "192.168.50.1#{i-1}"
      centos.vm.network "public_network", type: "dhcp", bridge: "wlxd0374517f383"
    end

    config.vm.define "db0#{i}" do |centos|
      centos.vm.box = "centos/8"
      centos.vm.hostname = "db0#{i}"
      # centos.vm.network "public_network", ip: "192.168.50.2#{i-1}"
      centos.vm.network "public_network", type: "dhcp", bridge: "wlxd0374517f383"
    end
  end

end
