Vagrant.configure("2") do |config|
    
    (10..11).each do |i|
        config.vm.define "ubuntu#{i}" do |ubuntu|
            ubuntu.vm.box = "ubuntu/bionic64"
            ubuntu.vm.network "private_network", ip: "192.168.50.#{i}"
        end
    end

    (20..21).each do |i|
        config.vm.define "centos#{i}" do |centos|
            centos.vm.box = "centos/8"
            centos.vm.network "private_network", ip: "192.168.50.#{i}"
        end
    end

end